spring.application.name=Product_Creation

kibo.tenant.id=52999
kibo.site.id=77922
kibo.client.id=1702
kibo.client.secret=4dde5fe8eb834acca5c7107fea4afdcf
kibo.tenant.host=t52999.sandbox.mozu.com
kibo.home.host=home.mozu.com
spring.devtools.restart.enabled=false

# Spring Batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always